<?php

namespace App\Traits;

use Illuminate\Http\Response;

trait ApiResponser
{
    /**
     * Gateway success response: return already-formatted API response
     *
     * @param mixed $data
     * @param int $code
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Response
     */
    public function successResponse($data, $code = Response::HTTP_OK)
    {
        // The gateway expects the microservice response already formatted,
        // so return it directly with correct content-type header.
        return response($data, $code)->header('Content-Type', 'application/json');
    }

    /**
     * Gateway error response generated by gateway itself
     *
     * @param string|array $message
     * @param int $code
     * @return \Illuminate\Http\JsonResponse
     */
    public function errorResponse($message, $code)
    {
        return response()->json([
            'error' => $message,
            'code'  => $code
        ], $code);
    }

    /**
     * Return error message produced by underlying API (pass-through)
     *
     * @param mixed $message
     * @param int $code
     * @return \Illuminate\Http\Response
     */
    public function errorMessage($message, $code)
    {
        return response($message, $code)->header('Content-Type', 'application/json');
    }
}
